Publication.find_or_create_by("title"=>"Teste", "description"=>"Testetefeçfj kçsdlfkjd çsdflkj", "body"=>"<p>dtetelk elrkejrerere eefefef<img alt=\"\" src=\"/ckeditor_assets/pictures/1/content_8843603-0-slide-mini-salad.png\" style=\"width: 538px; height: 534px;\" />fsdfsdfsdfsdfsdf</p>\r\n", "pub_type"=>"post", "pub_category"=>"text", "knowledge_area_id"=>1, "author_id"=>146, "image_file_name"=>"italian-food-16.png", "image_content_type"=>"image/png", "image_file_size"=>331457)
Publication.find_or_create_by("title"=>"Teste de publicação 2 ", "description"=>"um segundo tese de deojndsslfkjn çsjlkdna.s", "body"=>"<p>etwetrtrtwerwr</p>\r\n", "pub_type"=>nil, "pub_category"=>"mission_diary", "knowledge_area_id"=>1, "author_id"=>146, "image_file_name"=>"Anuncie-no-Programa-estética-na-Tv.png", "image_content_type"=>"image/png", "image_file_size"=>140921)
Publication.find_or_create_by("title"=>"Teste 232", "description"=>"wfsdf dsfdsf sd fsdf dsfsd", "body"=>"<p>sf muito LASJDHSA KDJAS DSd</p>\r\n", "pub_type"=>nil, "pub_category"=>"mission_diary", "knowledge_area_id"=>1, "author_id"=>146, "image_file_name"=>"bg_barramais.png", "image_content_type"=>"image/png", "image_file_size"=>707163)
Publication.find_or_create_by("title"=>"eteste", "description"=>"ttete", "body"=>"<p>tetete</p>\r\n", "pub_type"=>nil, "pub_category"=>"video", "knowledge_area_id"=>1, "author_id"=>142, "image_file_name"=>"italian-food-16.png", "image_content_type"=>"image/png", "image_file_size"=>331457)
Publication.find_or_create_by("title"=>"Riwurwyuryewi wiueguyegwr", "description"=>"sakjhaskdjhaskdjh ", "body"=>"<h1>sdasd<span style=\"color:#000080;\">asdsadasd dsadasds &nbsp;&nbsp;</span></h1>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><span style=\"color:#ff0000;\">sdasdsadasdsadsadsad</span></p>\r\n", "pub_type"=>"post", "pub_category"=>"video", "knowledge_area_id"=>1, "author_id"=>146, "image_file_name"=>"Anuncie-no-Programa-estética-na-Tv.png", "image_content_type"=>"image/png", "image_file_size"=>140921)
Publication.find_or_create_by("title"=>"Teste de Noticia", "description"=>"Este é um teste de publicação de uma noticia pelo admin do site.", "body"=>"<p><span style=\"color:#0000cd;\">Este &eacute; um teste de publica&ccedil;&atilde;o de uma noticia pelo admin do site.</span></p>\r\n", "pub_type"=>"news", "pub_category"=>"text", "knowledge_area_id"=>1, "author_id"=>146, "image_file_name"=>"restaurant_trikaya_in_bawdhan-pune.png", "image_content_type"=>"image/png", "image_file_size"=>530264)
User.create("email"=>"announcer@tudo.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"arthur.stefe@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"arthur@vortexdeveloper.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste10@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste20@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste7@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste8@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste31@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste32@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste22@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste23@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste34@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste35@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste36@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste37@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste39@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste40@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste41@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste42@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste43@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste44@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste45@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste46@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste47@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste48@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste49@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste50@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste51@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste52@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste54@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste55@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste56@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste57@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste58@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste59@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste60@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste62@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste63@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste64@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste65@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste67@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste70@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste71@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste73@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste74@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste75@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"comadsadsd@com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t1@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t2@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t3@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t4@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t5@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t6@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t7@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t8@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t10@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t11@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t20@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t23@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t30@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t31@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t1003@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t33@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t35@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"432423@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t45@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t56@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t60@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"t65@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a3@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a12@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a13@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a14@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a15@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a16@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a18@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a20@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a21@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a31@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a33@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a35@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a36@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a37@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a38@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a39@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a44@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a45@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a47@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a48@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a49@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a50@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a61@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a91@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"a92@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"admin@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"e@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b1@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b2@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b3@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b4@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b5@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b6@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b7@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b8@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b10@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b11@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b12@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"b20@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"arthur.foi@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"ba@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"ga@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"1@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"e1@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"3434@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"admin@admin.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"teste200@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"as@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"w1@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anunciante_zero@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anunciante1@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"abc@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anun1@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anun2@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anun3@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anun4@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anun5@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"dalsdkjasflj@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"dadsdlsdkjasflj@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"arthdadasdasda@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"arthursadasdad@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"empresa@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"empresa-old@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"assinanteapenas@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"colunistaapenas@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"colunistaapenas2@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"counistaapenas3@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"colunistaapenas4@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"assinanteapenas3@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anunciantenovo@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"anuncianteapenas3@teste.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"assinante@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"colunista@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"assinante0@gmail.com", "active"=>"unactive", 'password' => '123456')
User.create("email"=>"colunista0@gmail.com", "active"=>"unactive", 'password' => '123456')
Ad.find_or_create_by("description"=>"Caoisasxa a dsad asd asd asd as d", "title"=>"Anuncio de teste 1", "link"=>"", "text_description"=>"Caoisasxa a dsad asd asd asd as dCaoisasxa a dsad asd asd asd as dCaoisasxa a dsad asd asd asd as d", "price"=>5, "category_id"=>1, "announcer_id"=>37, "avatar_file_name"=>"Food-PNG.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>974861, "ad_type"=>"banner", "home"=>"s", "active"=>"sim")
Ad.find_or_create_by("description"=>"Teste de Anuncio 2 descrição", "title"=>"Teste de Anuncio 2", "link"=>"", "text_description"=>"Teste de Anuncio 2Teste de Anuncio 2Teste de Anuncio 2Teste de Anuncio 2Teste de Anuncio 2Teste de Anuncio 2Teste de Anuncio 2", "price"=>100, "category_id"=>1, "announcer_id"=>37, "avatar_file_name"=>"italian-food-16.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>331457, "ad_type"=>"normal", "home"=>"s", "active"=>"sim")
Ad.find_or_create_by("description"=>"Teste de Anuncio 3 descrição", "title"=>"Teste de Anuncio 3", "link"=>"", "text_description"=>"Teste de Anuncio 3 descriçãoTeste de Anuncio 3 descriçãoTeste de Anuncio 3 descriçãoTeste de Anuncio 3 descriçãoTeste de Anuncio 3 descrição", "price"=>200, "category_id"=>1, "announcer_id"=>37, "avatar_file_name"=>"8843603-0-slide-mini-salad.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>99555, "ad_type"=>"principal", "home"=>"s", "active"=>"sim")
Ad.find_or_create_by("description"=>"Teste de Anuncio 4 descrição", "title"=>"Teste de Anuncio 4", "link"=>"", "text_description"=>"Teste de Anuncio 4Teste de Anuncio 4Teste de Anuncio 4Teste de Anuncio 4Teste de Anuncio 4Teste de Anuncio 4Teste de Anuncio 4", "price"=>132, "category_id"=>2, "announcer_id"=>37, "avatar_file_name"=>"8843603-0-slide-mini-salad.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>99555, "ad_type"=>"normal", "home"=>"s", "active"=>"sim")
AdPlan.find_or_create_by("comercial"=>"Sim", "name"=>"Gold", "days"=>1, "value"=>1, "plan_type"=>"gold", "description"=>"Gold")
AdPlan.find_or_create_by("comercial"=>"Sim", "name"=>"Silver", "days"=>2, "value"=>3, "plan_type"=>"silver", "description"=>"Silver")
AdPlan.find_or_create_by("comercial"=>"Sim", "name"=>"Bronze", "days"=>1, "value"=>1, "plan_type"=>"bronze", "description"=>"Bronze")
Administrator.find_or_create_by("user_id"=>1)
Administrator.find_or_create_by("user_id"=>115)
Announcer.find_or_create_by("user_id"=>1, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>68, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>90, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>91, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>92, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>93, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>95, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>96, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>97, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>98, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>100, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>101, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>102, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>103, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>104, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>105, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>106, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>107, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>108, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>109, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>110, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>111, "name"=>nil, "fantasy_name"=>nil, "contact_name"=>nil, "doc_type"=>nil, "doc"=>nil, "email"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>112, "name"=>"e1", "fantasy_name"=>"e1", "contact_name"=>"e1", "doc_type"=>"cnpj", "doc"=>nil, "email"=>"e1", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>116, "name"=>"aas", "fantasy_name"=>"aas", "contact_name"=>"Aas", "doc_type"=>"cnpj", "doc"=>nil, "email"=>"aas", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>118, "name"=>"Anunciante Zero LTDA", "fantasy_name"=>"Anunciante Zero", "contact_name"=>"Arthur", "doc_type"=>"cnpj", "doc"=>nil, "email"=>"contato@anunciante_zero.com", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>119, "name"=>"Anunciante 1", "fantasy_name"=>"Anunciante 1", "contact_name"=>"Anunciante 1", "doc_type"=>nil, "doc"=>"123", "email"=>"anun@gmail.com", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>120, "name"=>"abc", "fantasy_name"=>"abc", "contact_name"=>"abc", "doc_type"=>"cnpj", "doc"=>nil, "email"=>"abc", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>121, "name"=>"123", "fantasy_name"=>"123", "contact_name"=>"123", "doc_type"=>"cnpj", "doc"=>nil, "email"=>"123", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>122, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>123, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>125, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>126, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>127, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>128, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>129, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>130, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Announcer.find_or_create_by("user_id"=>131, "name"=>"Empresa LTDA", "fantasy_name"=>"Empresa X", "contact_name"=>"Arthur Stefe", "doc_type"=>"cnpj", "doc"=>"123456", "email"=>"arthur.stefe@gmail.com", "avatar_file_name"=>"criar-anuncio.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>82346, "ad_plan_id"=>1, "about_text"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "banner_file_name"=>"Anuncie-no-Programa-estética-na-Tv.png", "banner_content_type"=>"image/png", "banner_file_size"=>140921)
Announcer.find_or_create_by("user_id"=>132, "name"=>"", "fantasy_name"=>"", "contact_name"=>"", "doc_type"=>nil, "doc"=>nil, "email"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "ad_plan_id"=>nil, "about_text"=>nil, "banner_file_name"=>nil, "banner_content_type"=>nil, "banner_file_size"=>nil)
Category.find_or_create_by("name"=>"Teste Cat 1", "father_id"=>nil)
Category.find_or_create_by("name"=>"Food", "father_id"=>nil)
Columnist.find_or_create_by("user_id"=>34, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>35, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>36, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>37, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>38, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>39, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>40, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>45, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>46, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>49, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>50, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>54, "periodicity"=>"3 por semana", "admin_info"=>"", "sex"=>"M", "admin_validate"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>55, "periodicity"=>"3", "admin_info"=>"", "sex"=>"M", "admin_validate"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>57, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>59, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>60, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>61, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>62, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>63, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>64, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>66, "periodicity"=>"", "admin_info"=>"", "sex"=>nil, "admin_validate"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>68, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>94, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>113, "periodicity"=>"1", "admin_info"=>"", "sex"=>"M", "admin_validate"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>117, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>139, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>142, "periodicity"=>nil, "admin_info"=>nil, "sex"=>nil, "admin_validate"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil, "columnist_title_id"=>nil)
Columnist.find_or_create_by("user_id"=>146, "periodicity"=>"", "admin_info"=>"", "sex"=>"", "admin_validate"=>"", "avatar_file_name"=>"user.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>10499, "columnist_title_id"=>nil)
Contact.find_or_create_by("name"=>"Arthur Stefe", "email"=>"arthur.stefe@gmail.com", "company"=>"Vortex", "phone"=>"2126674053", "message"=>"Teste")
Contact.find_or_create_by("name"=>"Arthur Stefe", "email"=>"arthur.stefe@gmail.com", "company"=>"Vortex", "phone"=>"21999354548", "message"=>"Teste")
Curriculum.find_or_create_by("title"=>"Teste de r", "description"=>"Teste de rTeste de rTeste de rTeste de rTeste de r", "subscriber_id"=>56, "file_file_name"=>"CHRISTIAN.pdf", "file_content_type"=>"application/pdf", "file_file_size"=>57726)
Gallery.find_or_create_by("image_file_name"=>"Food-PNG.png", "image_content_type"=>"image/png", "image_file_size"=>974861, "announcer_id"=>37)
Gallery.find_or_create_by("image_file_name"=>"Anuncie-no-Programa-estética-na-Tv.png", "image_content_type"=>"image/png", "image_file_size"=>140921, "announcer_id"=>37)
Gallery.find_or_create_by("image_file_name"=>"bg_barramais.png", "image_content_type"=>"image/png", "image_file_size"=>707163, "announcer_id"=>37)
Gallery.find_or_create_by("image_file_name"=>"Food-PNG.png", "image_content_type"=>"image/png", "image_file_size"=>974861, "announcer_id"=>37)
Gallery.find_or_create_by("image_file_name"=>"criar-anuncio.png", "image_content_type"=>"image/png", "image_file_size"=>82346, "announcer_id"=>37)
Gallery.find_or_create_by("image_file_name"=>"italian-food-16.png", "image_content_type"=>"image/png", "image_file_size"=>331457, "announcer_id"=>37)
Gallery.find_or_create_by("image_file_name"=>"italian-food-16.png", "image_content_type"=>"image/png", "image_file_size"=>331457, "announcer_id"=>37)
Gallery.find_or_create_by("image_file_name"=>"italian-food-16.png", "image_content_type"=>"image/png", "image_file_size"=>331457, "announcer_id"=>37)
Insider.find_or_create_by("user_id"=>1)
KnowledgeArea.find_or_create_by("name"=>"Teste")
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>1)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>2)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>3)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>4)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>5)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>6)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>7)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>8)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>9)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>10)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>11)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>12)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>13)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>14)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>15)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>16)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>17)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>18)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>19)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>20)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>21)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>22)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>23)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>24)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>25)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>26)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>27)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>28)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>29)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>30)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>31)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>32)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>33)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>34)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>35)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>36)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>37)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>38)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>39)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>40)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>41)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>42)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>43)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>44)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>45)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>46)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>47)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>48)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>49)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>50)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>51)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>52)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>53)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>54)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>55)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>56)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>57)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>58)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>59)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>60)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>61)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>62)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>63)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>64)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>65)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>66)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>67)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>68)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>69)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>70)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>71)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>72)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>73)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>74)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>75)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>76)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>77)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>78)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>79)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>80)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>81)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>82)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>83)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>84)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>85)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>86)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>87)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>88)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>89)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>90)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>91)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>92)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>93)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>94)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>95)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>96)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>97)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>98)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>99)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>100)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>101)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>102)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>103)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>104)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>105)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>106)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>107)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>108)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>109)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>110)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>111)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>112)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>113)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>114)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>115)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>116)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>117)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>118)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>119)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>120)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>121)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>122)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>123)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>124)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>125)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>126)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>127)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>128)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>129)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>130)
PersonalProfile.find_or_create_by("name"=>"João da empresa", "street"=>"SIlva", "complement"=>"23", "neighborhood"=>"Mato", "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>"23456789", "user_id"=>131)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>132)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>133)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>134)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>135)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>136)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>137)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>138)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>139)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>140)
PersonalProfile.find_or_create_by("name"=>"Assinante da Silva", "street"=>"3", "complement"=>"3", "neighborhood"=>"Mato", "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>"23445667", "user_id"=>141)
PersonalProfile.find_or_create_by("name"=>nil, "street"=>nil, "complement"=>nil, "neighborhood"=>nil, "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>nil, "user_id"=>142)
PersonalProfile.find_or_create_by("name"=>"Teste de perfil", "street"=>"", "complement"=>"", "neighborhood"=>"", "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>"", "user_id"=>145)
PersonalProfile.find_or_create_by("name"=>"Arthur", "street"=>"", "complement"=>"", "neighborhood"=>"", "city_id"=>nil, "state_id"=>nil, "country_id"=>nil, "zip_code"=>"", "user_id"=>146)
Phonebook.find_or_create_by("telephone_id"=>1, "personal_profile_id"=>nil)
Phonebook.find_or_create_by("telephone_id"=>1, "personal_profile_id"=>nil)
PubAttachment.find_or_create_by("publication_id"=>3, "file_file_name"=>"pecas-diversas-para-tv-led-lg-39-modelo-39ln5400-D_NQ_NP_108621-MLB20845734219_082016-O.webp", "file_content_type"=>"image/webp", "file_file_size"=>22886)
PubAttachment.find_or_create_by("publication_id"=>5, "file_file_name"=>nil, "file_content_type"=>nil, "file_file_size"=>nil)
PubAttachment.find_or_create_by("publication_id"=>6, "file_file_name"=>"PlayStation_1_Logo.png", "file_content_type"=>"image/png", "file_file_size"=>68729)
Role.find_or_create_by("name"=>"Administrator", "resource_type"=>nil, "resource_id"=>nil)
Role.find_or_create_by("name"=>"Announcer", "resource_type"=>nil, "resource_id"=>nil)
Role.find_or_create_by("name"=>"Insider", "resource_type"=>nil, "resource_id"=>nil)
Role.find_or_create_by("name"=>"Subscriber", "resource_type"=>nil, "resource_id"=>nil)
Role.find_or_create_by("name"=>"Columnist", "resource_type"=>nil, "resource_id"=>nil)
Subscriber.find_or_create_by("user_id"=>1, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>2, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>3, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>4, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>5, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>6, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>7, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>8, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>11, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>12, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>13, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>14, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>15, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>16, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>17, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>18, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>19, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>22, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>23, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>24, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>25, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>26, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>27, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>28, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>29, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>31, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>32, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>40, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>41, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>42, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>47, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>48, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>51, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>52, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>53, "christian"=>"S", "church"=>"Batista", "sex"=>"M", "christian_denomination"=>"Não sei", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>56, "christian"=>"S", "church"=>"Batista", "sex"=>"M", "christian_denomination"=>"Não sei", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>58, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>65, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>66, "christian"=>nil, "church"=>"", "sex"=>nil, "christian_denomination"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>67, "christian"=>nil, "church"=>"", "sex"=>nil, "christian_denomination"=>"", "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>68, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>55, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>69, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>91, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>99, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>114, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>116, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>135, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>136, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>137, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>138, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>140, "christian"=>nil, "church"=>nil, "sex"=>nil, "christian_denomination"=>nil, "avatar_file_name"=>nil, "avatar_content_type"=>nil, "avatar_file_size"=>nil)
Subscriber.find_or_create_by("user_id"=>141, "christian"=>"S", "church"=>"Batista", "sex"=>"M", "christian_denomination"=>"N\\A", "avatar_file_name"=>"PlayStation_1_Logo.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>68729)
Subscriber.find_or_create_by("user_id"=>145, "christian"=>"", "church"=>"", "sex"=>"", "christian_denomination"=>"", "avatar_file_name"=>"user.png", "avatar_content_type"=>"image/png", "avatar_file_size"=>10499)
Telephone.find_or_create_by("number"=>"21993990702", "name"=>nil)
Telephone.find_or_create_by("number"=>"5522999354548", "name"=>"Arthur")
Vacancy.find_or_create_by("name"=>"Coiasas", "description"=>"asdsad asd asd asd asdasd asdasda", "active"=>nil, "announcer_id"=>37)
Vacancy.find_or_create_by("name"=>"teterer", "description"=>"erewrew rwerewr ewr", "active"=>nil, "announcer_id"=>37)
Versicle.find_or_create_by("testament"=>"Antigo", "book"=>"Salmos", "chapter"=>"34", "versicle"=>"16", "text"=>"A face do Senhor está contra os que fazem o mal, para desarraigar da terra a memória deles.")
Versicle.find_or_create_by("testament"=>"Antigo", "book"=>"Salmos", "chapter"=>"34", "versicle"=>"17", "text"=>"Os justos clamam, e o Senhor os ouve, e os livra de todas as suas angústias.")
Versicle.find_or_create_by("testament"=>"Antigo", "book"=>"Salmos", "chapter"=>"34", "versicle"=>"18", "text"=>"Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito.")
